### ISSUE TITLE
[LXC] Ingress相关

### ISSUE THREAD

**Issue by WYang2018fly** [WYang2018fly/me#32]
# Kubernetes - Ingress

## 概念

> 部署了 deployment 和 Service，实现了对服务的访问，在实际使用中需要根据请求路径匹配访问不同的服务
>
> 为了达到这种类似负载均衡的效果，k8s 提供了另一个组件 —— [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)
>
> Ingress是一组允许外部请求进入集群的路由规则的集合。它可以给 Service 提供集群外部访问的 URL，负载均衡，SSL 终止等
>
> <img width="800" alt="ingress" src="https://user-images.githubusercontent.com/36754320/125182455-b8bb5080-e240-11eb-9db4-e4a85f2f41ca.png">
>
> **Ingress 与 type: LoadBalancer 的 Service 的区别**
>
> - Ingress 不是一种 Service 类型，而是 K8S 中的一种资源类型，直接通过` kubectl get ingress` 的方式获已有的 Ingress 资源
> - Ingress 可以通过多种[控制器(Ingress controller)](https://kubernetes.io/zh/docs/concepts/services-networking/ingress-controllers/)来实现

### 相关字段

```bash
➜  ~ kubectl explain ingress
KIND:     Ingress
VERSION:  networking.k8s.io/v1

DESCRIPTION:
     Ingress is a collection of rules that allow inbound connections to reach
     the endpoints defined by a backend. An Ingress can be configured to give
     services externally-reachable urls, load balance traffic, terminate SSL,
     offer name based virtual hosting etc.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec	<Object>
     Spec is the desired state of the Ingress. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

   status	<Object>
     Status is the current state of the Ingress. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

```

### 具体配置项

> - **metadata.annotations**
>
>    annotations 是 ingress 的主要配置项目，Ingress经常使用annotations来配置一些选项
>
>   配置项具体取决于Ingress 控制器，不同的Ingress控制器支持不同的注解
>
>   通过修改这些配置来修改ingress的行为，例如重定向[rewrite-target annotation](https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md)
>
> - **spec.rules** —— ingress配置路径转发的规则
>
>   每个HTTP规则都包含以下配置项：
>
>   - host：可选，未指定 host，该规则适用于通过指定 IP 地址的所有入站 HTTP 通信；提供了host（例如 foo.bar.com，[主机名配置通配符](https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#hostname-wildcards)），则rules只适用于指定的host
>
>   - paths：路由列表
>     - path：每个路径（可以是一个路径字符串，也可以是一个正则表达式）都有一个由 serviceName 和 servicePort 定义的关联beckend
>
>     - [pathType](https://kubernetes.io/zh/docs/concepts/services-networking/ingress/)：路径类型
>
>       Exact：精确匹配 URL 路径，且区分大小写
>
>       Prefix：基于以 / 分隔的 URL 路径前缀匹配
>
>       ImplementationSpecific：匹配方法取决于[IngressClass](https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#ingress-class)
>
>   - backend：指定service 服务，service.name 是服务名称， servic.port 是服务端口
>
> - **spec.DefaultBackend** —— ingress设置默认访问的 Service 服务
>
>   没有 rules 的 Ingress 将所有流量发送到同一个默认后端，defaultBackend通常是Ingress 控制器的配置选项，而非在 Ingress 资源中指定

### [Simple fanout](https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout)

> 根据请求的HTTP URI将来自同一IP地址的流量路由到多个Service

<img width="800" alt="fanout" src="https://user-images.githubusercontent.com/36754320/125182471-d8527900-e240-11eb-8cdf-e6f35aeb8be7.png">

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout-example
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 4200
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8080
```
