### ISSUE TITLE
[Microservice] Traefik相关配置

### ISSUE THREAD

**Issue by WYang2018fly** [WYang2018fly/me#43]
# Traefik related configuration

## 配置介绍

**分为两种**

- 动态（路由配置）

  系统如何处理请求的所有配置内容

  这些配置可以改变，无缝热更新，不会出现请求中断或失去连接的情况

- 静态（启动时的配置项）

  连接到 providers，定义 Treafik 监听的 entrypoints

  

**定义方式**

1. 配置文件

   启动时，Traefik会按以下顺序寻找traefik.yml(.yaml,.toml)文件

   - `/etc/traefik/`
   - `$XDG_CONFIG_HOME/`
   - `$HOME/.config/`
   - `.` (*the working directory*)

   自定义配置文件来覆盖默认的配置

   ```bash
   traefik --configFile=foo/bar/myconfigfile.yml
   ```

2. 命令行参数

   [Static Configuration: CLI](https://doc.traefik.io/traefik/reference/static-configuration/cli/)

3. 环境变量

   [Static Configuration: Environment variables](https://doc.traefik.io/traefik/reference/static-configuration/env/)

## 安装

> [Use the official Docker image](https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-official-docker-image)

**use docker image**

运行容器需要挂载一个配置文件的[sample]((https://raw.githubusercontent.com/traefik/traefik/v2.4/traefik.sample.yml))

```bash
➜  Downloads wget https://raw.githubusercontent.com/traefik/traefik/v2.4/traefik.sample.yml
--2021-08-18 14:14:15--  https://raw.githubusercontent.com/traefik/traefik/v2.4/traefik.sample.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3374 (3.3K) [text/plain]
Saving to: ‘traefik.sample.yml’

traefik.sample.yml                      100%[=============================================================================>]   3.29K  --.-KB/s    in 0s      

2021-08-18 14:14:16 (13.7 MB/s) - ‘traefik.sample.yml’ saved [3374/3374]

➜  Downloads cp traefik.sample.yml traefik.yaml       
➜  Downloads ls
traefik.sample.yml traefik.yaml
➜  Downloads code traefik.yaml
```

traefik.yaml

```yaml
# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# EntryPoints configuration
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    
# API and dashboard configuration
api:
    insecure: true
    dashboard: true
    
# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
```

run container

```bash
➜  Downloads docker run -d -p 8080:8080 -p 80:80 -v $PWD/traefik.yaml:/etc/traefik/traefik.yaml --name traefik traefik:v2.4
9481e914ef78588a4d460b7079bd5de8256222729ebf54154053b4f06e468310

➜  Downloads docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS         PORTS                                                                                                                                      NAMES
9481e914ef78   traefik:v2.4             "/entrypoint.sh trae…"   4 seconds ago   Up 3 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                               traefik
```

<img width="1427" alt="dashboard" src="https://user-images.githubusercontent.com/36754320/130350338-e04eceef-2a21-4e2a-901b-82c6ad49be24.png">

### Overview

> **how**
>
> Configuration discovery in Traefik is achieved through *Providers*
>
> The *providers* are infrastructure components, whether orchestrators, container engines, cloud providers, or key-value stores
>
> **why**
>
> The idea is that Traefik queries the provider APIs in order to find relevant information about routing
>
> when Traefik detects a change, it dynamically updates the routes

provider 可以分为的四种类型：

- Label-based: 每个部署的容器有一组绑定的label (docker)
- Key-Value-based: each deployed container updates a key-value store with relevant information
- Annotation-based:  a separate object, with annotations, defines the characteristics of the container

- File-based: 使用文件定义配置

### **Traefik & Docker**

> Attach labels to your containers and let Traefik do the rest!

#### 路由配置

Traefik使用容器的labels来检索[路由配置](https://doc.traefik.io/traefik/routing/providers/docker/#routing-configuration)

#### Provider配置

**endpoint**

Required, Default="unix:///var/run/docker.sock"

```yaml
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
```

**useBindPortIP**

Optional, Default=false

Traefik 将请求路由到匹配容器的 IP/Port

当设置 useBindPortIP=true 时，Traefik 使用连接到容器的 binding 的 IP/Port，而不是其内部网络的 IP/Port

```yaml
providers:
  docker:
    useBindPortIP: true
```

**exposedByDefault**

Optional, Default=true

默认情况下通过 Traefik 暴露容器。如果设置为 false，没有 traefik.enable=true 标签的容器则会被最终的路由配置所忽略

```yaml
providers:
  docker:
    exposedByDefault: false
```

**network**

Optional, Default=""

定义用于连接所有容器的默认 docker 网络。也可以使用容器标签 traefik.docker.network 来覆盖该选项

```yaml
providers:
  docker:
    network: test
```

**defaultRule**

Optional, Default=Host(`{{ normalize .Name }}`)

对于一个特定的容器，如果标签没有定义任何路由规则，则由 defaultRule 来代替

容器服务名称可以作为 Name 标识来访问，并且模板可以访问该容器上定义的所有标签

```yaml
providers:
  docker:
    defaultRule: "Host(`{{ .Name }}.{{ index .Labels \"customLabel\"}}`)"
```

**httpClientTimeout**

Optional, Default=0

定义客户端http连接超时时长，如果值为0即不设置

```yaml
providers:
  docker:
    httpClientTimeout: 300
```

**constraints**

> Restrict the Scope of Service Discovery

Optional, Default=""

约束是 Traefik 和容器标签匹配的一个表达式，用来确定是否为该容器创建路由信息

- 容器的标签不匹配表达式的话，就不会创建容器的路由

- 表达式为空，则包括所有检测到的容器（不过滤）

表达式语法基于 Tag(`tag`) 和 TagRegex(`tag`) 函数以及通常的布尔逻辑

```yaml
providers:
  docker:
    constraints: "Label(`a.label.name`,`foo`)"
```

**[tls](https://doc.traefik.io/traefik/providers/docker/#tls)**

### Overview

> start Traefik
>
> 1. define **entrypoints**
> 2. connected to these **entrypoints**
> 3. **routers** analyze the incoming requests to see if they match a set of rules
> 4. the router might transform the request using pieces of **middleware** before forwarding them to your **services**
>
> 
>
> **Clear Responsibilities**
>
> - Providers discover the services that live on your infrastructure (their IP, health, ...)
> - Entrypoints listen for incoming traffic (ports, ...)
> - Routers analyse the requests (host, path, headers, SSL, ...)
> - Services forward the request to your services (load balancing, ...)
> - Middlewares may update the request or make decisions based on the request (authentication, rate limiting, headers, ...)

### EntryPoints

> EntryPoints are the network entry points into Traefik
>
> They define the port which will receive the packets, and whether to listen for TCP or UDP
>
> EntryPoints are part of the static configuration
>
> [配置方式](https://doc.traefik.io/traefik/routing/entrypoints/#configuration)

```yaml
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
```

**General**

```yaml
## Static configuration
entryPoints:
  name:
    address: ":8888" # same as ":8888/tcp"
    enableHTTP3: true
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42
        graceTimeOut: 42
      respondingTimeouts:
        readTimeout: 42
        writeTimeout: 42
        idleTimeout: 42
    proxyProtocol:
      insecure: true
      trustedIPs:
        - "127.0.0.1"
        - "192.168.0.1"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "127.0.0.1"
        - "192.168.0.1"
```

#### 配置EntryPoints

如果没有指定，HTTP 路由将接受来自所有定义的入口点的请求

如果要想将路由范围限制为一组入口点，需要设置entryPoints选项

**监听所有的EntryPoints**

```yaml
# Dynamic configuration
http:
  routers:
    Router-1:
      # By default, routers listen to every entry points
      rule: "Host(`example.com`)"
      service: "service-1"
      
# Static configuration  
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  other:
    address: ":9090"
```

**监听指定的EntryPoints**

```yaml
# Dynamic configuration
http:
  routers:
    Router-1:
      # won't listen to entry point web
      entryPoints:
        - "websecure"
        - "other"
      rule: "Host(`example.com`)"
      service: "service-1"

# Static configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  other:
    address: ":9090"
```

#### 配置 [Rule](https://doc.traefik.io/traefik/routing/routers/#rule)

规则是一组配置的匹配项，用于确定特定请求是否符合特定标准

如果规则得到验证，路由器就会激活，调用中间件，然后将请求转发给服务

#### 配置 [Middlewares](https://doc.traefik.io/traefik/routing/routers/#middlewares)

可以在每个HTTP路由器上附上一个中间件列表

只有当规则匹配时，并且在将请求转发给服务之前，中间件才会生效

### Services - HTTP Services

服务负责配置如何到达最终将处理传入请求的实际服务

```yaml
## Dynamic configuration
http:
  services:
    my-service:
      loadBalancer:
        servers:
        - url: "http://<private-ip-server-1>:<private-port-server-1>/"
        - url: "http://<private-ip-server-2>:<private-port-server-2>/"
```

## Middlewares

> 中间件被附件到路由上，是一种在请求发送到你的 服务 之前（或者在服务的响应发送到客户端之前）调整请求的一种方法
>
> Traefik 内置了许多不同功能的中间件，其中一些可以修改请求，头信息，一些负责重定向，一些添加身份验证等等

[HTTP Middlewares](https://doc.traefik.io/traefik/middlewares/http/overview/#http-middlewares)

#### AddPrefix

在转发请求之前先更新请求的 URL 路径

```yaml
# Prefixing with /foo
labels:
  - "traefik.http.middlewares.add-foo.addprefix.prefix=/foo"
```

#### BasicAuth

限制已知用户对服务的访问权限

```yaml
# Declaring the user list
#
# Note: all dollar signs in the hash need to be doubled for escaping.
# To create a user:password pair, the following command can be used:
# echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
labels:
  - "traefik.http.middlewares.test-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/,test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"
```

......
