### ISSUE TITLE
[Microservice] Traefik实践

### ISSUE THREAD

**Issue by WYang2018fly** [WYang2018fly/me#44]
# Traefik实践

> 在[demo_docker-compose_v2](https://github.com/WYang2018fly/demo_docker-compose_v2)的基础上，使app和service之间通过traefik进行通信

## 目录结构

```bash
.
├── README.md
├── app
│   ├── Dockerfile
│   ├── bootstrap.sh
│   ├── my_app
│   │   ├── README.md
│   │   ├── build
│   │   │   ├── asset-manifest.json
│   │   │   ├── favicon.ico
│   │   │   ├── index.html
│   │   │   ├── logo192.png
│   │   │   ├── logo512.png
│   │   │   ├── manifest.json
│   │   │   ├── robots.txt
│   │   │   ├── runtime.config.js
│   │   │   └── static
│   │   │       ├── css
│   │   │       │   ├── 2.97a13557.chunk.css
│   │   │       │   ├── 2.97a13557.chunk.css.map
│   │   │       │   ├── main.08613c9b.chunk.css
│   │   │       │   └── main.08613c9b.chunk.css.map
│   │   │       └── js
│   │   │           ├── 2.e02c0939.chunk.js
│   │   │           ├── 2.e02c0939.chunk.js.LICENSE.txt
│   │   │           ├── 2.e02c0939.chunk.js.map
│   │   │           ├── 3.0f2f319a.chunk.js
│   │   │           ├── 3.0f2f319a.chunk.js.map
│   │   │           ├── main.6c3a5cff.chunk.js
│   │   │           ├── main.6c3a5cff.chunk.js.map
│   │   │           ├── runtime-main.89519d8b.js
│   │   │           └── runtime-main.89519d8b.js.map
│   │   ├── package.json
│   │   ├── public
│   │   │   ├── favicon.ico
│   │   │   ├── index.html
│   │   │   ├── logo192.png
│   │   │   ├── logo512.png
│   │   │   ├── manifest.json
│   │   │   ├── robots.txt
│   │   │   └── runtime.config.js
│   │   ├── src
│   │   │   ├── App.css
│   │   │   ├── App.js
│   │   │   ├── App.test.js
│   │   │   ├── components
│   │   │   │   └── MyTab.js
│   │   │   ├── index.css
│   │   │   ├── index.js
│   │   │   ├── reportWebVitals.js
│   │   │   └── setupTests.js
│   │   └── yarn.lock
│   └── nginx_conf
│       └── app.conf
├── docker-compose.yaml
├── service
│   ├── service_conf
│   │   └── production.yaml
│   ├── task
│   │   ├── Dockerfile
│   │   ├── config
│   │   │   └── default.yaml
│   │   ├── dist
│   │   │   ├── bundle.js
│   │   │   └── config
│   │   │       └── default.yaml
│   │   ├── index.js
│   │   ├── package.json
│   │   ├── src
│   │   │   ├── model
│   │   │   │   ├── Task.js
│   │   │   │   ├── User.js
│   │   │   │   └── index.js
│   │   │   └── router
│   │   │       └── index.js
│   │   ├── webpack.config.js
│   │   └── yarn.lock
│   └── user
│       ├── Dockerfile
│       ├── config
│       │   └── default.yaml
│       ├── dist
│       │   ├── bundle.js
│       │   └── config
│       │       └── default.yaml
│       ├── index.js
│       ├── package.json
│       ├── src
│       │   ├── model
│       │   │   ├── User.js
│       │   │   └── index.js
│       │   └── router
│       │       └── index.js
│       ├── webpack.config.js
│       └── yarn.lock
└── traefik.yaml
```

## 静态配置

**traefik.yaml**

```yaml
## STATIC CONFIGURATION

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# EntryPoints configuration
entryPoints:
  app:
    address: :80
  service:
    address: :19007
    
# API and dashboard configuration
api:
  insecure: true
  dashboard: true
    
# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # Do not expose containers unless explicitly told so
    exposedByDefault: false
```

**使用docker-compose启动traefik**

```yaml
version: "3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    # command:
    #   - "--providers.docker=true"
    environment: 
       - "SVC_TRAEFIK_URL=http://localhost:19007"
    ports:
      - "80:80"
      - "8080:8080"
      - "19007:19007"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
```

## 动态配置

```yaml
#...
services:
  svc-user:
    image: svc-user:latest
    restart: always
    volumes: 
      - ./service/service_conf/production.yaml:/service/config/production.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svc-user.entrypoints=service"
      - "traefik.http.routers.svc-user.rule=PathPrefix(`/api/users`)"
      # - "traefik.http.routers.svc-user.middlewares=svc-user-stripprefix"
      # - "traefik.http.middlewares.svc-user-stripprefix.stripprefix.prefixes=/api/user"
      # - "traefik.http.middlewares.svc-user-stripprefix.stripprefix.forceSlash=false"
      - "traefik.http.services.svc-user.loadbalancer.server.port=9007"
      
  svc-task:
    image: svc-task:latest
    restart: always
    volumes: 
      - ./service/service_conf/production.yaml:/service/config/production.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svc-task.entrypoints=service"
      - "traefik.http.routers.svc-task.rule=PathPrefix(`/api/tasks`)"
      # - "traefik.http.routers.svc-task.middlewares=svc-task-stripprefix"
      # - "traefik.http.middlewares.svc-task-stripprefix.stripprefix.prefixes=/api/task"
      # - "traefik.http.middlewares.svc-task-stripprefix.stripprefix.forceSlash=false"
      - "traefik.http.services.svc-task.loadbalancer.server.port=9008"

  web-myapp:
    image: app-my_app:latest
    restart: always
    # ports:
    # - "80:80"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.web-myapp.rule=Host(`myapp.example.com`)"
      - "traefik.http.routers.web-myapp.entrypoints=app"
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
    depends_on: 
      - svc-user
      - svc-task
```

## 验证

**启动服务**

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker compose -f docker-compose.yaml -p demo_v2 up -d
[+] Running 4/4
 ⠿ Container demo_v2_svc-task_1               Running                                                                                                    0.0s
 ⠿ Container 1bf23b6e3d99_demo_v2_svc-user_1  Running                                                                                                    0.0s
 ⠿ Container traefik                          Running                                                                                                    0.0s
 ⠿ Container demo_v2_web-myapp_1              Started   
 
➜  demo_docker-compose_v2 git:(master) docker compose ls
NAME                STATUS
demo_v2             running(4)
```

**访问服务**

```bash
➜  demo_docker-compose_v2 git:(master) curl localhost 
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>React App</title><link href="/static/css/2.97a13557.chunk.css" rel="stylesheet"><link href="/static/css/main.08613c9b.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><script src="./runtime.config.js"></script><div id="root"></div><script>!function(e){function r(r){for(var n,a,i=r[0],c=r[1],l=r[2],p=0,s=[];p<i.length;p++)a=i[p],Object.prototype.hasOwnProperty.call(o,a)&&o[a]&&s.push(o[a][0]),o[a]=0;for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(f&&f(r);s.length;)s.shift()();return u.push.apply(u,l||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,i=1;i<t.length;i++){var c=t[i];0!==o[c]&&(n=!1)}n&&(u.splice(r--,1),e=a(a.s=t[0]))}return e}var n={},o={1:0},u=[];function a(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,a),t.l=!0,t.exports}a.e=function(e){var r=[],t=o[e];if(0!==t)if(t)r.push(t[2]);else{var n=new Promise((function(r,n){t=o[e]=[r,n]}));r.push(t[2]=n);var u,i=document.createElement("script");i.charset="utf-8",i.timeout=120,a.nc&&i.setAttribute("nonce",a.nc),i.src=function(e){return a.p+"static/js/"+({}[e]||e)+"."+{3:"0f2f319a"}[e]+".chunk.js"}(e);var c=new Error;u=function(r){i.onerror=i.onload=null,clearTimeout(l);var t=o[e];if(0!==t){if(t){var n=r&&("load"===r.type?"missing":r.type),u=r&&r.target&&r.target.src;c.message="Loading chunk "+e+" failed.\n("+n+": "+u+")",c.name="ChunkLoadError",c.type=n,c.request=u,t[1](c)}o[e]=void 0}};var l=setTimeout((function(){u({type:"timeout",target:i})}),12e4);i.onerror=i.onload=u,document.head.appendChild(i)}return Promise.all(r)},a.m=e,a.c=n,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(e,r){if(1&r&&(e=a(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)a.d(t,n,function(r){return e[r]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/",a.oe=function(e){throw console.error(e),e};var i=this.webpackJsonpmy_app=this.webpackJsonpmy_app||[],c=i.push.bind(i);i.push=r,i=i.slice();for(var l=0;l<i.length;l++)r(i[l]);var f=c;t()}([])</script><script src="/static/js/2.e02c0939.chunk.js"></script><script src="/static/js/main.6c3a5cff.chunk.js"></script></body></html>% 

➜  demo_docker-compose_v2 git:(master) curl localhost:19007/api/users
[{"_id":"6118f9b250e87e46495cfc6b","name":"wyang","code":"1521058","__v":0}]%

➜  demo_docker-compose_v2 git:(master) curl localhost:19007/api/tasks
[{"isFinish":true,"_id":"6118fe967938688961da5c9a","user":{"_id":"6118f9b250e87e46495cfc6b","name":"wyang"},"content":"task-xxx","__v":0},{"isFinish":false,"_id":"611a3dadf7072af012281eba","user":{"_id":"6118f9b250e87e46495cfc6b","name":"wyang"},"content":"task-xxxxxx","__v":0}]%  
```

### 1. 静态文件注入变量

在public目录下创建runtime.config.js文件，在index.html中引入，执行`yarn build`后会在dist下生成runtime.config.js

```bash
window.SVC_BASE_URL= {
  User: 'http://localhost:9007',
  Task: 'http://localhost:9008'
};
```

```html
<script src='./runtime.config.js'></script>
```

### 2. 动态追加变量

在Dockerfile的CMD中配置执行该脚本，这样通过my_app镜像创建出容器的同时会在runtime.config.js文本末尾追加内容

```dockerfile
FROM nginx:latest

ENV PORT=80 

WORKDIR /app

COPY ./my_app/build /var/www/my_app
COPY ./nginx_conf/app.conf /etc/nginx/conf.d/default.conf
COPY ./bootstrap.sh /

EXPOSE $PORT
CMD ["/bin/bash", "/bootstrap.sh"]
```

```sh
#!/usr/bin/env sh
echo "start frontend @bootstrap"
cat >> /var/www/my_app/runtime.config.js <<EOF
window.SVC_TRAEFIK_URL = 'http://localhost:19007';
EOF
nginx -g "daemon off;"
```

### 3. API调用

```js
let userResponse = await axios({
  method: 'get',
  url: `${window.SVC_TRAEFIK_URL ? window.SVC_TRAEFIK_URL : window.SVC_BASE_URLS.User}/api/users`
});
//...
```

**参考阅读**

- [Docker 学习 (Part 4 - Traefik)](https://github.com/nonocast/me/issues/183)
