### ISSUE TITLE
[LXC] network in docker compose

### ISSUE THREAD

**Issue by WYang2018fly** [WYang2018fly/me#45]
# docker compose network

## 配置项

- **driver**

  网络驱动

  - bridge: 多个容器在同一个Docker主机上，容器相互之间可以通过服务名访问
  - overlay: 多个容器运行在不同的Docker主机上，使集群服务能够相互通信
  - host: 容器直接使用主机网络通信
  - none: 容器禁用网络

- **ipam**

  IPAM(IP address management)配置

  ```yaml
  networks:
      app_net:
        driver: bridge
      ipam:
        config:
          - subnet: 172.28.0.0/16 # 子网配置，gateway配置version: "3"不支持
  ```

- **external**

  如果设置为true，使用外部已经创建好的network，docker compose不会尝试去创建它，如果不存在就会报错

  ```yaml
  networks:
    outside:
      external: true
  ```

- **name**

  为network设置自定义的名称，The name field can be used to reference networks which contain special characters.

  ```yaml
  networks:
    network1:
      name: my-app-net
  ```

- ......

### **准备：安装ping和ifconfig工具**

```bash
# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://security.debian.org/debian-security buster/updates/main arm64 Packages [297 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:5 http://deb.debian.org/debian buster/main arm64 Packages [7735 kB]
Get:6 http://deb.debian.org/debian buster-updates/main arm64 Packages [14.5 kB]
Fetched 8286 kB in 3s (2457 kB/s)                         
Reading package lists... Done

# apt-get install iputils-ping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcap2 libcap2-bin libpam-cap
The following NEW packages will be installed:
  iputils-ping libcap2 libcap2-bin libpam-cap
0 upgraded, 4 newly installed, 0 to remove and 2 not upgraded.
Need to get 103 kB of archives.
After this operation, 287 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian buster/main arm64 libcap2 arm64 1:2.25-2 [17.5 kB]
Get:2 http://deb.debian.org/debian buster/main arm64 iputils-ping arm64 3:20180629-2+deb10u2 [43.0 kB]
Get:3 http://deb.debian.org/debian buster/main arm64 libcap2-bin arm64 1:2.25-2 [28.5 kB]
Get:4 http://deb.debian.org/debian buster/main arm64 libpam-cap arm64 1:2.25-2 [14.3 kB]
Fetched 103 kB in 0s (229 kB/s)      
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcap2:arm64.
(Reading database ... 7631 files and directories currently installed.)
Preparing to unpack .../libcap2_1%3a2.25-2_arm64.deb ...
Unpacking libcap2:arm64 (1:2.25-2) ...
Selecting previously unselected package iputils-ping.
Preparing to unpack .../iputils-ping_3%3a20180629-2+deb10u2_arm64.deb ...
Unpacking iputils-ping (3:20180629-2+deb10u2) ...
Selecting previously unselected package libcap2-bin.
Preparing to unpack .../libcap2-bin_1%3a2.25-2_arm64.deb ...
Unpacking libcap2-bin (1:2.25-2) ...
Selecting previously unselected package libpam-cap:arm64.
Preparing to unpack .../libpam-cap_1%3a2.25-2_arm64.deb ...
Unpacking libpam-cap:arm64 (1:2.25-2) ...
Setting up libcap2:arm64 (1:2.25-2) ...
Setting up libcap2-bin (1:2.25-2) ...
Setting up libpam-cap:arm64 (1:2.25-2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/aarch64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/aarch64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up iputils-ping (3:20180629-2+deb10u2) ...
Processing triggers for libc-bin (2.28-10) ...

# apt-get install net-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 247 kB of archives.
After this operation, 974 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main arm64 net-tools arm64 1.60+git20180626.aebd88e-1 [247 kB]
Fetched 247 kB in 0s (553 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package net-tools.
(Reading database ... 7671 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60+git20180626.aebd88e-1_arm64.deb ...
Unpacking net-tools (1.60+git20180626.aebd88e-1) ...
Setting up net-tools (1.60+git20180626.aebd88e-1) ...
```

### **1. 默认的network**

docker-compose.yaml中不配置network，会创建一个默认的network(docker-compose-network_default)，driver类型为bridge，容器会自动加入该network

```bash
➜  demo_docker-compose_v2 git:(master) docker compose -f docker-compose.yaml -p docker-compose-network up -d
[+] Running 5/5
 ⠿ Network docker-compose-network_default        Created                                                                                    0.0s
 ⠿ Container docker-compose-network_svc-user_1   Started                                                                                    0.6s
 ⠿ Container traefik                             Started                                                                                    0.8s
 ⠿ Container docker-compose-network_svc-task_1   Started                                                                                    0.7s
 ⠿ Container docker-compose-network_web-myapp_1  Started                                                                                    1.3s 
```

```bash
➜  docker-compose-network docker network ls
NETWORK ID     NAME                             DRIVER    SCOPE
f7c3be7e8cd8   docker-compose-network_default   bridge    local

➜  demo_docker-compose_v2 git:(master) docker network inspect f7c3be7e8cd8
[
    {
        "Name": "docker-compose-network_default",
        "Id": "f7c3be7e8cd8b38725018253f0c915fd468cbae070400bfcb283a5baf19d5902",
        "Created": "2021-08-30T06:29:15.877245843Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.0.0/20",
                    "Gateway": "192.168.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0254d8ff0630635b904823bdcac8c6fdc69b4ef2916b8ebff747a45a0707c494": {
                "Name": "docker-compose-network_svc-task_1",
                "EndpointID": "ce1949c446b54e170a431615902d7cc7ec26e7e03669550a16d717fd7bdbf1b3",
                "MacAddress": "02:42:c0:a8:00:04",
                "IPv4Address": "192.168.0.4/20",
                "IPv6Address": ""
            },
            "3553ab6be72847469039c8c5a8e0ea89a79b351f2b720c70a7ac2beb54b805b6": {
                "Name": "docker-compose-network_svc-user_1",
                "EndpointID": "9790cc0992114fe3827a0cc6df51c6a97265db9d68d632b266ac9615dec4b732",
                "MacAddress": "02:42:c0:a8:00:02",
                "IPv4Address": "192.168.0.2/20",
                "IPv6Address": ""
            },
            "6f85643bbf96f909e9143d868411d479d99337069067aabb304fc94512c17c1c": {
                "Name": "traefik",
                "EndpointID": "c0c4fd68f31d7c828d8f349d79867dd3be746bee19488bf0bef02346679f8696",
                "MacAddress": "02:42:c0:a8:00:03",
                "IPv4Address": "192.168.0.3/20",
                "IPv6Address": ""
            },
            "8f217c4ab228764fd72db477249bc146a4a15e25f9a8dd3136e31c4fe4ae56e5": {
                "Name": "docker-compose-network_web-myapp_1",
                "EndpointID": "c38584c162a1f993d2168001016160788e9cc0b37b9e688c5def5cb0e2ad5923",
                "MacAddress": "02:42:c0:a8:00:05",
                "IPv4Address": "192.168.0.5/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "docker-compose-network",
            "com.docker.compose.version": "2.0.0"
        }
    }
]
```

容器之间可以通过service name进行访问

```bash
➜  demo_docker-compose_v2 git:(master) docker exec -it 8f217c4ab228 /bin/bash
root@8f217c4ab228:/app# ping -c 4 svc-user
PING svc-user (192.168.0.2) 56(84) bytes of data.
64 bytes from docker-compose-network_svc-user_1.docker-compose-network_default (192.168.0.2): icmp_seq=1 ttl=64 time=0.921 ms
64 bytes from docker-compose-network_svc-user_1.docker-compose-network_default (192.168.0.2): icmp_seq=2 ttl=64 time=0.233 ms
64 bytes from docker-compose-network_svc-user_1.docker-compose-network_default (192.168.0.2): icmp_seq=3 ttl=64 time=0.230 ms
64 bytes from docker-compose-network_svc-user_1.docker-compose-network_default (192.168.0.2): icmp_seq=4 ttl=64 time=0.333 ms

--- svc-user ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 50ms
rtt min/avg/max/mdev = 0.230/0.429/0.921/0.287 ms
```

### **2. 使用links定义别名**

```yaml
services:
  web-myapp:
    # ...
    links:
      - "svc-task:task"
```

web-myapp容器可以使用task作为host去访问svc-task容器

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker exec -it 995c6db0960a /bin/bash
root@995c6db0960a:/app# ping -c 4 task
PING task (192.168.80.4) 56(84) bytes of data.
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_default (192.168.80.4): icmp_seq=1 ttl=64 time=0.106 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_default (192.168.80.4): icmp_seq=2 ttl=64 time=0.272 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_default (192.168.80.4): icmp_seq=3 ttl=64 time=0.300 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_default (192.168.80.4): icmp_seq=4 ttl=64 time=0.271 ms

--- task ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 88ms
rtt min/avg/max/mdev = 0.106/0.237/0.300/0.077 ms
```

#### 网络隔离

```yaml
services:
  svc-user:
    #...
    networks:
      - svc
   
  svc-task:
    #...
    networks:
      - svc

  web-myapp:
    #...
    networks:
      - app
      - svc

networks:
  app:
    driver: bridge
  svc:
    driver: bridge
```

app容器可以访问service容器

```bash
root@082f1450492f:/app# ping -c 4 svc-user
PING svc-user (192.168.144.2) 56(84) bytes of data.
64 bytes from demo_docker-compose_v2_svc-user_1.demo_docker-compose_v2_svc (192.168.144.2): icmp_seq=1 ttl=64 time=0.224 ms
64 bytes from demo_docker-compose_v2_svc-user_1.demo_docker-compose_v2_svc (192.168.144.2): icmp_seq=2 ttl=64 time=0.226 ms
64 bytes from demo_docker-compose_v2_svc-user_1.demo_docker-compose_v2_svc (192.168.144.2): icmp_seq=3 ttl=64 time=0.283 ms
64 bytes from demo_docker-compose_v2_svc-user_1.demo_docker-compose_v2_svc (192.168.144.2): icmp_seq=4 ttl=64 time=0.288 ms

--- svc-user ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 73ms
rtt min/avg/max/mdev = 0.224/0.255/0.288/0.032 ms

root@082f1450492f:/app# ping -c 4 svc-task
PING svc-task (192.168.144.3) 56(84) bytes of data.
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_svc (192.168.144.3): icmp_seq=1 ttl=64 time=0.225 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_svc (192.168.144.3): icmp_seq=2 ttl=64 time=0.274 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_svc (192.168.144.3): icmp_seq=3 ttl=64 time=0.343 ms
64 bytes from demo_docker-compose_v2_svc-task_1.demo_docker-compose_v2_svc (192.168.144.3): icmp_seq=4 ttl=64 time=0.285 ms

--- svc-task ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 45ms
rtt min/avg/max/mdev = 0.225/0.281/0.343/0.046 ms
```

user service容器不能访问app容器，可以访问task service容器

```bash
root@1b30be53b393:/service# ping app-my_app
ping: app-my_app: Name or service not known

root@1b30be53b393:/service# ping -c 4 svc-task
PING svc-task (192.168.144.3) 56(84) bytes of data.
64 bytes from 1b30be53b393 (192.168.144.3): icmp_seq=1 ttl=64 time=0.069 ms
64 bytes from 1b30be53b393 (192.168.144.3): icmp_seq=2 ttl=64 time=0.171 ms
64 bytes from 1b30be53b393 (192.168.144.3): icmp_seq=3 ttl=64 time=0.148 ms
64 bytes from 1b30be53b393 (192.168.144.3): icmp_seq=4 ttl=64 time=0.187 ms

--- svc-task ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3083ms
rtt min/avg/max/mdev = 0.069/0.143/0.187/0.047 ms
```

#### 配置容器的静态ip

```yaml
services:
  svc-user:
    #...
    networks:
      svc:
        ipv4_address: 172.28.0.2
   
  svc-task:
    #...
    networks:
      svc:
        ipv4_address: 172.28.0.3

  web-myapp:
    #...
    networks:
      - app
      - svc
      
networks:
    app:
    driver: bridge
  svc:
    driver: bridge
    ipam: 
      config: 
      - subnet: 172.28.0.0/16
```

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker network ls
NETWORK ID     NAME                             DRIVER    SCOPE
4a9bad20592b   demo_docker-compose_v2_app       bridge    local
848c945087bd   demo_docker-compose_v2_svc       bridge    local

➜  demo_docker-compose_v2 git:(master) ✗ docker network inspect 848c945087bd
[
    {
        "Name": "demo_docker-compose_v2_svc",
        "Id": "848c945087bd13b0fc7821964c8c97035c75b4a382cc2d9c1049304c6ab207b3",
        "Created": "2021-08-31T03:42:30.14570601Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.28.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "09d70e99dca90abf03f0a77b64bab9c40bb816c348a3b51f547d8d8db12d790b": {
                "Name": "demo_docker-compose_v2_svc-user_1",
                "EndpointID": "c5f6106a4d0c95831e6137ac093c5353ebaa4ea4223c01f2b18d81ed371c20f3",
                "MacAddress": "02:42:ac:1c:00:02",
                "IPv4Address": "172.28.0.2/16",
                "IPv6Address": ""
            },
            "76f9c178f4632dcaab538bfc5097fb6043e6039716dcdcc0803d2e23479ba47d": {
                "Name": "demo_docker-compose_v2_svc-task_1",
                "EndpointID": "9a22abacdbe79190541b9db71e08a2238a69b3f75459ef3e26a7be13ca2c421c",
                "MacAddress": "02:42:ac:1c:00:03",
                "IPv4Address": "172.28.0.3/16",
                "IPv6Address": ""
            },
            "c85c694b2bc7c5fc5f3b313464836e497c777e5da2b0b8341774f7f7204dd1c0": {
                "Name": "demo_docker-compose_v2_web-myapp_1",
                "EndpointID": "46e7816a0c40ec648f8a1af965342048e5c83cdbd5528f68d45abd155ef75b56",
                "MacAddress": "02:42:ac:1c:00:04",
                "IPv4Address": "172.28.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "svc",
            "com.docker.compose.project": "demo_docker-compose_v2",
            "com.docker.compose.version": "1.29.2"
        }
    }
]
```

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker exec -it c85c694b2bc7 /bin/bash            
# app container
root@c85c694b2bc7:/app# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500 # network app
        inet 192.168.192.2  netmask 255.255.240.0  broadcast 192.168.207.255
        ether 02:42:c0:a8:c0:02  txqueuelen 0  (Ethernet)
        RX packets 6069  bytes 8972205 (8.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2248  bytes 123512 (120.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500 # network svc
        inet 172.28.0.4  netmask 255.255.0.0  broadcast 172.28.255.255
        ether 02:42:ac:1c:00:04  txqueuelen 0  (Ethernet)
        RX packets 17  bytes 1366 (1.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 716 (716.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 716 (716.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# svc_user container
➜  demo_docker-compose_v2 git:(master) ✗ docker exec -it 09d70e99dca9 /bin/bash 
root@09d70e99dca9:/service# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500 # network svc
        inet 172.28.0.2  netmask 255.255.0.0  broadcast 172.28.255.255
        ether 02:42:ac:1c:00:02  txqueuelen 0  (Ethernet)
        RX packets 6787  bytes 8724470 (8.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3920  bytes 252329 (246.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 13  bytes 1107 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13  bytes 1107 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

### 4. 配置默认network

traefik容器未配置network，默认加入demo_docker-compose_v2_default

```yaml
➜  demo_docker-compose_v2 git:(master) ✗ docker network inspect 39b247650b61
[
    {
        "Name": "demo_docker-compose_v2_default",
        "Id": "39b247650b61804dd764ab5855e5b56948f48ea4735482d2fe06f08bccf3b2af",
        "Created": "2021-08-31T03:42:30.223748176Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.208.0/20",
                    "Gateway": "192.168.208.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "b0bf10d50c46ac55fa49528d8811f428b302988bb797bc528cccf7510afe5035": {
                "Name": "traefik",
                "EndpointID": "0a4a3d7c3c64e98ac3658eaa8ed8ac067edeace2ac428fb2bc286b6e7fb96e81",
                "MacAddress": "02:42:c0:a8:d0:02",
                "IPv4Address": "192.168.208.2/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "demo_docker-compose_v2",
            "com.docker.compose.version": "1.29.2"
        }
    }
]
```

创建my_network

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker network --help

Usage:  docker network COMMAND

Manage networks

Commands:
  connect     Connect a container to a network
  create      Create a network
  disconnect  Disconnect a container from a network
  inspect     Display detailed information on one or more networks
  ls          List networks
  prune       Remove all unused networks
  rm          Remove one or more networks

Run 'docker network COMMAND --help' for more information on a command.

➜  demo_docker-compose_v2 git:(master) ✗ docker network create my_net
3d08af6cd88ac024127b2f1c6e82df374d2f44c53625700428662043e8adae74
➜  demo_docker-compose_v2 git:(master) ✗ docker network ls
NETWORK ID     NAME                             DRIVER    SCOPE
3d08af6cd88a   my_net                           bridge    local
```

```yaml
#...
networks:
  app:
    driver: bridge
  svc:
    driver: bridge
    ipam: 
      config: 
      - subnet: 172.28.0.0/16
  default:
    external: true
    name: my_net
```

此时重新执行`docker-compose up -d`，traefik容器会加入已创建的my_net

```bash
➜  demo_docker-compose_v2 git:(master) ✗ docker network ls
NETWORK ID     NAME                             DRIVER    SCOPE
39b247650b61   demo_docker-compose_v2_default   bridge    local
3d08af6cd88a   my_net                           bridge    local

➜  demo_docker-compose_v2 git:(master) ✗ docker network inspect 39b247650b61  
[
    {
        "Name": "demo_docker-compose_v2_default",
        "Id": "39b247650b61804dd764ab5855e5b56948f48ea4735482d2fe06f08bccf3b2af",
        "Created": "2021-08-31T03:42:30.223748176Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.208.0/20",
                    "Gateway": "192.168.208.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "demo_docker-compose_v2",
            "com.docker.compose.version": "1.29.2"
        }
    }
]
➜  demo_docker-compose_v2 git:(master) ✗ docker network inspect 3d08af6cd88a
[
    {
        "Name": "my_net",
        "Id": "3d08af6cd88ac024127b2f1c6e82df374d2f44c53625700428662043e8adae74",
        "Created": "2021-08-31T05:59:03.638255762Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.224.0/20",
                    "Gateway": "192.168.224.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "36ad3d918d905e63a231e5713556175956859a14d049cac6da3cc0b7eb6a3ab3": {
                "Name": "traefik",
                "EndpointID": "af87d815b5ca5f88fbc0c6a6bc57494a3dd9d63db0d700677d92ed38d82f3311",
                "MacAddress": "02:42:c0:a8:e0:02",
                "IPv4Address": "192.168.224.2/20",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

**参考阅读**

- [Networking in Compose](https://docs.docker.com/compose/networking/)
- [Network configuration reference](https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference)
