### ISSUE TITLE
PV与PVC (draft)

### ISSUE THREAD

**Issue by WYang2018fly** [WYang2018fly/me#59]
**pv-upload.yaml**

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-upload
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
          - node2
```

**pvc-upload.yaml**

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: s365-bytedance
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
```

**backend/deployment.yaml**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: s365-bytedance
  labels:
    app: backend
spec:
  replicas: 8
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # ...
          volumeMounts:
            # ...
            - name: shared-data
              mountPath: /backend/uploads/
      volumes:
        # ...
        - name: shared-data
          persistentVolumeClaim:
            claimName: pvc-upload
```

```bash
# master
➜  kubernates kubectl get node -o wide
NAME     STATUS   ROLES                  AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
master   Ready    control-plane,master   46d   v1.22.4   172.16.30.185   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   docker://20.10.11
node1    Ready    <none>                 46d   v1.22.4   172.16.30.186   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   docker://20.10.11
node2    Ready    <none>                 46d   v1.22.4   172.16.30.187   <none>        Ubuntu 20.04.3 LTS   5.4.0-92-generic   docker://20.10.11

➜  kubernates kubectl get pods -o wide -n s365-bytedance
NAME                      READY   STATUS    RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
apps-6c845c79b8-4xmpz     1/1     Running   0          23h     10.244.2.189   node2   <none>           <none>
backend-b9f946954-2v5hk   1/1     Running   0          7m22s   10.244.2.195   node2   <none>           <none>
backend-b9f946954-6mjww   1/1     Running   0          7m22s   10.244.1.162   node1   <none>           <none>
backend-b9f946954-74lxn   1/1     Running   0          6m6s    10.244.1.165   node1   <none>           <none>
backend-b9f946954-7zr9s   1/1     Running   0          6m6s    10.244.2.197   node2   <none>           <none>
backend-b9f946954-bddrc   1/1     Running   0          6m15s   10.244.1.163   node1   <none>           <none>
backend-b9f946954-cbhz8   1/1     Running   0          7m22s   10.244.2.196   node2   <none>           <none>
backend-b9f946954-fgrbf   1/1     Running   0          7m22s   10.244.1.161   node1   <none>           <none>
backend-b9f946954-ptrdw   1/1     Running   0          6m7s    10.244.1.164   node1   <none>           <none>
gateway-94d84d849-472xg   1/1     Running   0          24h     10.244.2.186   node2   <none>           <none>
```

```bash
# node1
➜  Desktop ssh shgbit@172.16.30.186
shgbit@172.16.30.186's password: 
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat 22 Jan 2022 01:40:03 PM CST

  System load:  0.66               Users logged in:          0
  Usage of /:   61.5% of 48.47GB   IPv4 address for cni0:    10.244.1.1
  Memory usage: 24%                IPv4 address for docker0: 172.17.0.1
  Swap usage:   0%                 IPv4 address for ens160:  172.16.30.186
  Processes:    339

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

53 updates can be applied immediately.
5 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable


*** System restart required ***
Last login: Tue Jan  4 16:20:16 2022 from 172.16.25.125
shgbit@node1:~$ ls /tmp/2022/01/
file-1642829849.xlsx  file-1642829861.xlsx  file-1642830408.xlsx
```
